---
- name: Configure repos; Install packages; System administration
  hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/packages.yml
    - vars/repos.yml

  tasks:
    - include_tasks: tasks/config.yml
      tags: config

    - include_tasks: tasks/packages.yml
      tags: packages



- name: User configuration
  hosts: localhost
  vars_files:
    - vars/user.yml
    - vars/repos.yml

  tasks:
    - include_tasks: tasks/user.yml
      tags: user
