---
# - name: Set system-wide environment variable to enable Firefox hardware video acceleration
#   lineinfile:
#     path: /etc/environment
#     line: MOZ_X11_EGL=1
#   tags: config

# - name: Copy 00-fix-dbus.sh
#   copy:
#     src: 00-fix-dbus.sh
#     dest: /etc/X11/xinit/xinitrc.d
#     mode: '0755'
#   tags: config

# - name: Copy v4l2loopback.conf
#   copy:
#     src: v4l2loopback.conf
#     dest: /etc/modprobe.d
#     mode: '0644'
#   tags: config

- name: Insert/Update DNF configuration block in /etc/dnf/dnf.conf
  blockinfile:
    path: /etc/dnf/dnf.conf
    block: |
      fastestmirror=1
      max_parallel_downloads=20
      deltarpm=true