---
- name: 'Configuration | Disable grub graphical (rhgb) boot'
  become: yes
  lineinfile:
    dest: '/etc/default/grub'
    line: 'GRUB_CMDLINE_LINUX="\1\3"'
    regexp: '^GRUB_CMDLINE_LINUX="(.*)( )?rhgb(.*)"$'
    backrefs: yes
    state: 'present'
  tags: [ 'grub', 'configuration' ]

- name: 'Configuration | Update grub2 configuration file'
  become: yes
  command: '/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg'
  tags: [ 'grub', 'configuration' ]
