---
- name: DNF | Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: DNF | Install essential packages that extend the minimal installation
  dnf:
    name: "{{ core }}"
    state: present
  tags: core

- name: DNF | Install printing support
  dnf:
    name: "{{ printing }}"
    state: present
  tags: printing

- name: DNF | Install virtualization environment (virt-manager)
  dnf:
    name: "{{ virtualization }}"
    state: present
  tags: virtualization

- name: DNF | Install development environment
  dnf:
    name: "{{ dev_tools }}"
    state: present
  tags: dev_tools

- name: DNF | Install command-line utilities
  dnf:
    name: "{{ cli_tools }}"
    state: present
  tags: cli_tools

- name: DNF | Install applications that make up an i3 desktop environment
  dnf:
    name: "{{ i3_packages }}"
    state: present
  tags: i3

- name: DNF | Install GUI applications
  dnf:
    name: "{{ extra_packages }}"
    state: present
  tags: extras

- name: DNF | Install packages only available through RPMFusion (free)
  dnf:
    name: "{{ rpmfusion_packages }}"
    state: present
  tags: rpmfusion

- name: DNF | Install dawid/better_fonts from Fedora Copr
  dnf:
    name: "{{ better_fonts }}"
    state: present
  tags: [ copr, better_fonts ]

- name: DNF | Install gagbo/kitty-latest from Fedora Copr
  dnf:
    name: "{{ kitty }}"
    state: present
  tags: [ copr, kitty ]