---
- name: 'DNF | Upgrade system'
  become: yes
  dnf:
    name: '*'
    state: 'latest'
  tags: 'packages'

- name: 'DNF | Install wireless firmware (ThinkPad X220) and wireless tools'
  become: yes
  dnf:
    name: [ 'iwl6000g2a-firmware' , 'NetworkManager-wifi', 'nm-connection-editor' ]
    state: 'present'
  tags: [ 'packages', 'firmware', 'wifi' ]

- name: 'DNF | Install package groups'
  become: yes
  dnf:
    name: [ '@development-tools', '@multimedia', '@printing', '@standard', '@virtualization' ]
    state: 'present'
  tags: [ 'packages', 'groups' ]

- name: 'DNF | Install xorg packages'
  become: yes
  dnf:
    name: [ 'mesa-dri-drivers', 'xorg-x11-drv-libinput', 'xorg-x11-server-Xorg', 'xorg-x11-utils', 'xorg-x11-xinit' ]
    state: 'present'
  tags: [ 'packages', 'xorg' ]

- name: 'DNF | Install desktop packages'
  become: yes
  dnf:
    name: [ 'compton', 'dunst', 'feh', 'i3', 'i3status', 'light', 'polkit-gnome', 'redshift', 'rofi', 'scrot', 'udiskie' ]
    state: 'present'
  tags: [ 'packages', 'desktop' ]

- name: 'DNF | Install fontconfig'
  become: yes
  dnf:
    name: [ 'fontconfig-enhanced-defaults', 'fontconfig-font-replacements' ]
    state: 'present'
  tags: [ 'packages', 'fonts' ]

- name: 'DNF | Install extra packages'
  become: yes
  dnf:
    name: [ 'ImageMagick', 'ShellCheck', 'arandr', 'atool', 'ffmpeg', 'firefox', 'htop', 'java-1.8.0-openjdk', 'keepassxc', 'kitty', 'libreoffice-writer', 'mediainfo', 'mpv', 'neofetch', 'neovim', 'nnn', 'pavucontrol', 'pmount', 'simplescreenrecorder', 'stow', 'sxiv', 'transmission-gtk', 'xclip', 'youtube-dl', 'zathura', 'zathura-pdf-poppler' ]
    state: 'present'
  tags: [ 'packages', 'extra' ]
