---
# - name: Disable Fedora Modular repos
#   lineinfile:
#     path: "/etc/yum.repos.d/{{ item }}"
#     regexp: '^enabled=1'
#     line: enabled=0
#   with_items: "{{ repo_modular }}"
#   tags: packages

- name: Add/Enable RPM Fusion Free repository
  dnf:
    name: "{{ repo_rpmfusion }}"
    state: present
    disable_gpg_check: yes
  tags: packages


- name: Add Microsoft GPG key
  rpm_key:
    state: present
    key: "{{ rpm_key_microsoft }}"
  tags: packages

- name: Add/Enable VSCode YUM repository
  yum_repository:
    file: vscode
    name: code
    description: Visual Studio Code
    baseurl: "{{ repo_vscode }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ rpm_key_microsoft }}"
  tags: packages

- name: Add brave GPG key
  rpm_key:
    state: present
    key: "{{ key_brave }}"
  tags: packages

- name: Add/Enable brave YUM repository
  yum_repository:
    file: brave
    name: brave-browser
    description: Brave browser
    baseurl: "{{ repo_brave }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ key_brave }}"
  tags: packages


- name: Add/Enable qgis Copr
  command: "dnf copr enable -y {{ copr_qgis }}"
  args:
    creates: "/etc/yum.repos.d/{{ repo_qgis }}"
    warn: no
  tags: packages

# - name: Add/Enable better_fonts Copr
#   command: "dnf copr enable -y {{ copr_better_fonts }}"
#   args:
#     creates: "/etc/yum.repos.d/{{ repo_better_fonts }}"
#     warn: no
#   tags: packages

# - name: Add/Enable Iosevka Copr
#   command: "dnf copr enable -y {{ copr_iosevka }}"
#   args:
#     creates: "/etc/yum.repos.d/{{ repo_iosevka }}"
#     warn: no
#   tags: packages

- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: present
  tags: packages

- name: Install multimedia codecs
  dnf:
    name: '@Multimedia'
    state: present

- name: Install virtualization
  dnf:
    name: '@Virtualization'
    state: present

- name: Enable Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "{{ repo_flathub }}"
  tags: 
    - packages
    - flatpak

# TODO: Use list of names https://github.com/ansible-collections/community.general/pull/267
- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
  with_items: "{{ flatpaks }}"
  tags:
    - packages
    - flatpak

# - name: Autoremove unrequired packages installed as dependencies
#   dnf:
#     autoremove: true
#     state: absent
#   tags: packages
