---
- name: DNF | Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: DNF | Install development tools
  dnf:
    name: "{{ dev_packages }}"
    state: present
  tags: dev-tools

- name: DNF | Install CLI tools
  dnf:
    name: "{{ cli_tools }}"
    state: present
  tags: cli-tools

- name: DNF | Install i3wm packages
  dnf:
    name: "{{ i3_packages }}"
    state: present
  tags: i3

- name: DNF | Install extra packages
  dnf:
    name: "{{ extra_packages }}"
    state: present
  tags: extras

- name: DNF | Install packages from RPM Fusion free
  dnf:
    name: "{{ rpmfusion_packages }}"
    state: present
  tags: rpmfusion

- name: DNF | Install packages from Fedora Copr
  dnf:
    name: "{{ copr_packages }}"
    state: present
  tags: copr

- name: Flatpak | Install packages from Flathub
  flatpak:
    name: "{{ flatpak_apps }}"
  tags: flatpak