---
- name: 'RPM Fusion | Add RPM Fusion GPG key'
  become: yes
  rpm_key:
    state: 'present'
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}"
  tags: [ 'repos', 'rpmfusion' ]

- name: 'RPM Fusion | Install RPM Fusion free'
  become: yes
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: 'present'
  tags: [ 'repos', 'rpmfusion', 'free' ]

- name: 'Fedora Copr | Enable Copr repo for better_fonts by dawid'
  become: yes
  command: 'dnf copr enable -y dawid/better_fonts'
  args:
    creates: '/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:dawid:better_fonts.repo'
  tags: [ 'repos', 'copr', 'fonts' ]

- name: 'Fedora Copr | Enable Copr repo for kitty-latest by gagbo'
  become: yes
  command: 'dnf copr enable -y gagbo/kitty-latest'
  args:
    creates: '/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:gagbo:kitty-latest.repo'
  tags: [ 'repos', 'copr', 'kitty' ]
