---
- name: RPM Fusion | Enable RPM Fusion free repository
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  tags: rpmfusion

- name: Flatpak | Enable Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  tags: flatpak

- name: Fedora Copr | Enable Copr repository for dawid/better_fonts
  command: dnf copr enable -y dawid/better_fonts
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:dawid:better_fonts.repo
  tags: copr