---
- name: 'Configuration | Enable Periodic TRIM for SSDs'
  become: yes
  systemd:
    name: 'fstrim.timer'
    state: 'started'
    enabled: yes
  tags: [ 'configuration', 'systemd', 'ssd' ]

- name: 'Configuration | Reduce sysctl swappiness'
  become: yes
  lineinfile:
    path: '/etc/sysctl.d/99-sysctl.conf'
    line: 'vm.swappiness=1'
  tags: [ 'configuration', 'sysctl' ]

- name: 'Configuration | Disable grub graphical (rhgb) boot'
  become: yes
  lineinfile:
    dest: '/etc/default/grub'
    line: 'GRUB_CMDLINE_LINUX="\1\3"'
    regexp: '^GRUB_CMDLINE_LINUX="(.*)( )?rhgb(.*)"$'
    backrefs: yes
    state: 'present'
  register: 'grub'
  tags: [ 'configuration', 'grub' ]

- name: 'Configuration | Update grub2 configuration file'
  become: yes
  command: '/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg'
  when: 'grub.changed'
  tags: [ 'configuration', 'grub' ]
