---
- name: 'systemd | Enable fstrim timer (Periodic TRIM for SSDs)'
  become: yes
  systemd:
    name: 'fstrim.timer'
    state: 'started'
    enabled: yes

- name: 'Configuration | Reduce sysctl swappiness'
  become: yes
  lineinfile:
    path: '/etc/sysctl.d/99-sysctl.conf'
    line: 'vm.swappiness=1'
