---
# - name: Change login shell to zsh
#   user:
#     name: "{{ user }}"
#     shell: /usr/bin/zsh
#   become: yes
#   tags: user

# - name: Create zsh history directory
#   file:
#     path: "{{ data_dir }}/zsh"
#     state: directory
#     mode: '0755'
#   tags: user

# - name: Create zsh cache directory
#   file:
#     path: "{{ cache_dir }}/zsh"
#     state: directory
#     mode: '0755'
#   tags: user

# - name: Create local bin directory
#   file:
#     path: "{{ home_dir }}/bin"
#     state: directory
#     mode: '0755'
#   tags: user

# - name: Download networkmanager_dmenu script from GitHub
#   get_url:
#     url: "{{ repo_networkmanager_dmenu }}"
#     dest: "{{ home_dir }}/bin"
#     mode: '0775'
#   tags: user

- name: Create fonts directory
  file:
    path: "{{ data_dir }}/fonts"
    state: directory
    mode: '0755'
  tags: user

- name: Fetch latest release of Font Awesome fonts from GitHub
  uri:
    url: "{{ repo_fontawesome }}"
    return_content: true
  register: json_response
  tags: user

- name: Download and extract Font Awesome desktop fonts
  unarchive:
    src: "{{ json_response.json.assets[0].browser_download_url }}"
    dest: "{{ data_dir }}/fonts"
    remote_src: yes
  tags: user

# - name: Pull dotfiles from GitHub
#   git:
#     repo: "{{ repo_dotfiles }}"
#     dest: "{{ home_dir }}/dotfiles"
#   tags: user


##TODO add the starship config file to home_dir/.config/
# - name: Pull dotfiles from Starship 
#   git:
#     repo: "{{ repo_dotfiles }}"
#     dest: "{{ home_dir }}/dotfiles"
#   tags: user
