---
- hosts: all

  pre_tasks:
    - name: Ensure build dependencies are installed
      dnf:
        name: "{{ item }}"
        state: installed
      with_items:
        - "@Development tools"
        - tar
        - unzip
        - sudo
        - which
      when: ansible_distribution == 'Fedora'

  roles:
    - bootstrap_role
